server:
  port: ${PORT:8080}

spring:
  application:
    name: api-cinemagazine
  profiles:
    active: ${PROFILE:local}
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/cinemagazine}

tmdb:
  language: pt-BR
  key: ${API_KEY}
  host: ${TMDB_HOST:http://api.themoviedb.org/3}
  image: https://image.tmdb.org/t/p/original

jwt:
  secret: ${JWT_SECRET:aMH%Q#LHJL@oCWZko@x)+cYk,r:}kHz@T6rlj4st&UA(rZS:B**.KFY|yW[Aer@zOUBz?uJ5*JnZi7Xk}
  expiration:
    access-token: 5
    refresh-token: 1440

management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true
